apiVersion: v1
kind: ConfigMap
metadata:
  namespace: cdash
  name: my-cert.key
data:
  my-cert.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC6viOtjw2O3Uy6
    b0Gz0eO78/bh+Lr8+HtTWL8keIE04pZCphgMbZw7U5mfBLk3hx86eGTE43lEmP/9
    hA+BH/aeO4Ce7ELs1frJtfiLw512lV/TBVy8OLbaChISD/YZjtodbXd4MIO0xZtj
    nnDFjIoPhpEP+RGf3ALFYuErPY1T9AvsXf7B70VJr3ZSDmQS+KbNyXMbXft7IIwi
    p+2ginVWRWFKvYP9k6tY1She1GTThOzBdAjirMGJBTpsQaOrwYlg9NH1Uu/vgtZV
    X/xfLgeRe1ZZIWzGUT8JRc/B3biKUfDAaULRRYHYG3WFmQ0akugk88/2oQNG+97z
    /8037RWTAgMBAAECggEATuRbIEyqNqvpaW3tPPG0G0hzCX5SSOMU/t4kSl0agOQl
    BN00lbOM6EdmRBbzxLCyEbqhH8jWB5P3ufubrTp6rtiGex1nHLU9sQ/OhAVNNbbf
    d7/xMJdpMG5GuhjCKIQAQ6Rmb4FXcvx0rD5YeCzqeqqoCC56MqX5Cbi/Vcw4M7nR
    /QYYgFCrtjQQdP4kutAt7HIhQfcn12bBZV7+wbMPoG47vHuShZQo0/JsrucMots1
    PJ7P/FpPZGuRzDiuOWj4Fi2zO1fVUg4MlsMrQ1JfIDgIVXD9FD9rSFg/leetMB3w
    9qDjo+dSGULAobeAyVF+JNa6zPEZzN2nbBp41vrpaQKBgQDvSJvKad3B7ZKrNUwy
    Tkea4BL/XBINEa6q/qiOox/jqUjDR/lC9JUBiiUO1sIEpCCqi95PFQv2nY9Kdock
    shJtoeVKUbnuN9dG+oFapomeFYLEEQllOxzhKVqGwO4Ha+uvxXrCOA+tOL65bt0q
    Dc6BC9vCg8VEnQZ5w9GbFK1txQKBgQDHyeFGsadGGtO25kr1MAEHX6dBDKMrz5UQ
    LMl9/suwM8LMkXEvnSZc4Lvykv55Du367C2/GYvJoLbyCs4yEIB7/4I+bVccrjLY
    PEH2riH2WEwwZ/GwmXLIcuH+TVN8RO+8Lkb6FiCEnBAOjS09qhkmNtl1f9dKXYQS
    Ky3hywrDdwKBgQDb9F+Y8jXxtQP0s3qGZ6S0vjNYXvcM4mswLgUdkN+Yc506PSfp
    H1D1aFpmSI1ynLiWbRn+kfc8TFtSdKAH4FTGSGKwLW3/h38xdMaBYMLx+Q4KUyrS
    zkLeyxe29RQY6GBvY9VTQRtP/PB9HmbY6HYh85egN2aXisxQE+vSZXCCjQKBgQCl
    Rg1VVQuiw/iWWmZx9Lc1KV0MQ+8MBBo1GkfJMinAZuFkJ4ExuVgOB1+TqSRYcxBN
    vmmNqA1qy8fr7SJsahhP+6v8BqnEsRqgpSCQd7biumK0vJhE1nwM9HSd0cwZhlGo
    I8RViE54RT5HO2TMmVVato8oU4x/GWNzQEMhgb0yuwKBgQDhCL92KCaHjsHbMXO3
    2N6W/GA5zIzxEEjTa5X1NQztBDthNHSdAlDnkyob/Us+70nEBmoQICYlrCajo5zc
    VSZrz5f5MF2vQXFZR/yCYrHXqEQov7TfWenVLND9/mb01OQTK+5WG/NyJ5e6zw5k
    I6oyzduJ/Em8WcKUqorQX8SceA==
    -----END PRIVATE KEY-----

