apiVersion: v1
kind: ConfigMap
metadata:
  namespace: cdash
  name: my-cert.pem
data:
  my-cert.pem: |
    -----BEGIN CERTIFICATE-----
    MIIDazCCAlOgAwIBAgIUb7bl7dz1Rf8eEQ8VGv8dEPhUHKgwDQYJKoZIhvcNAQEL
    BQAwRTELMAkGA1UEBhMCTkwxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM
    GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAeFw0yNDAyMTIyMjI4NTNaFw0zNDAy
    MDkyMjI4NTNaMEUxCzAJBgNVBAYTAk5MMRMwEQYDVQQIDApTb21lLVN0YXRlMSEw
    HwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggEiMA0GCSqGSIb3DQEB
    AQUAA4IBDwAwggEKAoIBAQC6viOtjw2O3Uy6b0Gz0eO78/bh+Lr8+HtTWL8keIE0
    4pZCphgMbZw7U5mfBLk3hx86eGTE43lEmP/9hA+BH/aeO4Ce7ELs1frJtfiLw512
    lV/TBVy8OLbaChISD/YZjtodbXd4MIO0xZtjnnDFjIoPhpEP+RGf3ALFYuErPY1T
    9AvsXf7B70VJr3ZSDmQS+KbNyXMbXft7IIwip+2ginVWRWFKvYP9k6tY1She1GTT
    hOzBdAjirMGJBTpsQaOrwYlg9NH1Uu/vgtZVX/xfLgeRe1ZZIWzGUT8JRc/B3biK
    UfDAaULRRYHYG3WFmQ0akugk88/2oQNG+97z/8037RWTAgMBAAGjUzBRMB0GA1Ud
    DgQWBBT3EwO3SteS10SxpTTKEj7/Zj7NwDAfBgNVHSMEGDAWgBT3EwO3SteS10Sx
    pTTKEj7/Zj7NwDAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQCq
    gf5IOFpjP34L0mFpPW8ZrEqaRrU4wQu5JNG1M8EzhaiX56v660eNZD7Wsdbxebb4
    vMLSmKoyv7n7gWpDPIc28pNayUcylsFfEzsxmp4mHGg0rKhMgIbCd6GCELKmSmP8
    khqIsCdhV/FPbxbMFuDHpzqaHamqmmIXCLxj+fJZgC/ozNHCCIZRT3QKwpFmmrkR
    FuYrY2QbGsBzGGf0Z9SoQXs2+dB6fQ5aT5mEHdfer5UyHhLOPZj6rWWM22EKN8ws
    z/bobIgSOnVp0yDt6FGahR1AoYCCj30+CpoxB+eCENX/mak4PpsMWyE5I9gZRd5A
    zTz/k0RMQoF7I4cKASH7
    -----END CERTIFICATE-----

