apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cdash-worker
  name: cdash-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdash-worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cdash-worker
    spec:
      containers:
        - env:
            - name: APP_DEBUG
              value: "true"
            - name: APP_URL
              value: "{{ .Values.worker.protocol }}://{{ .Values.application.host }}"
            - name: APP_KEY
              value: {{ .Values.application.appkey }}
            - name: DB_CONNECTION
              value: {{ .Values.database.connection }}
            - name: DB_DATABASE
              value: {{ .Values.database.name }}
            - name: DB_HOST
              value: {{ .Values.database.host }}
            - name: DB_USERNAME
              value: {{ .Values.database.username }}
            - name: DB_PASSWORD
              value: {{ .Values.database.password }}
            - name: DB_PORT
              value: {{ .Values.database.port | quote }}
            - name: QUEUE_CONNECTION
              value: {{ .Values.worker.connection }}
            - name: REMOTE_WORKERS
              value: {{ .Values.worker.remote | quote }}
            - name: FILESYSTEM_DRIVER
              value: local
          image: "{{ .Values.image.repository }}-worker:{{ .Values.image.version }}"
          name: cdash-worker
          resources: {}
          volumeMounts:
            - name: cdash-my-cert-pem
              mountPath: "/var/www/my-cert.pem"
              subPath: my-cert.pem
              readOnly: false
            - name: cdash-my-cert-key
              mountPath: "/var/www/my-cert.key"
              subPath: my-cert.key
              readOnly: false
            - mountPath: /var/lib/cdash
              name: cdashdata
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "php artisan storage:mkdirs"]
      restartPolicy: Always
      volumes:
        - name: cdashdata
          persistentVolumeClaim:
            claimName: cdashdata
        {{- if .Values.application.tls }}
        - name: cdash-my-cert-key
          {{- if .Values.application.key_secret }}
          secret:
            secretName: {{ .Values.application.key_secret }}
          {{- else}}
          configMap:
            name: my-cert.key
          {{- end}}
        - name: cdash-my-cert-pem
          {{- if .Values.application.pem_secret }}
          secret:
            secretName: {{ .Values.application.pem_secret }}
          {{- else}}
          configMap:
            name: my-cert.pem
          {{- end}}
        {{- end}}

status: {}
